name: CI Workflow
description: "Shared CI workflow."

inputs:
  cargo-flags:
    description: "Flags to pass to cargo commands."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Check formatting
      shell: bash
      run: cargo fmt --check

    - name: Run tests
      shell: bash
      run: cargo test ${{ inputs.cargo-flags }}

    - name: Run clippy checks
      shell: bash
      run: cargo clippy ${{ inputs.cargo-flags }} -- -D warnings
